# Welcome to Jekyll!
#
title: "Simbian Consulting Blog"
subtitle: "InfoLease, Unidata/PICK Basic, and Tech Tips"
name: "Ian McGowan"
email: "ian@simbian.org"
description: "A blog about using, exploring and programming InfoLease and legacy systems"
url: "https://ianmcgowan.github.io"
repository: "ianmcgowan/ianmcgowan.github.io"

# Site Author
author:
  name: "Ian McGowan"
  avatar: "/assets/images/profile.jpg"  # Add a photo later
  bio: "Consultant specializing in InfoLease and Unidata/PICK Basic systems"
  email: "ian@simbian.org"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ianmcgowan"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/ianmcgowan"  # Update with your profile

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
